// Blob-mixer material presets — every numeric / colour value is interpolatable
// so PresetTransition can lerp between any two presets each frame without
// snapping any property.

export type BlobPreset = {
    id: string;
    name: string;
    swatch: string;
    bg: string;
    accent: string;
    material: {
        color: string;
        metalness: number;
        roughness: number;
        envMapIntensity: number;
        clearcoat: number;
        clearcoatRoughness: number;
        iridescence: number;
        iridescenceIOR: number;
        iridescenceThicknessRange: [number, number];
        sheen: number;
        sheenColor: string;
        sheenRoughness: number;
        transmission: number;
        thickness: number;
        ior: number;
        attenuationColor: string;
        attenuationDistance: number;
        specularIntensity: number;
        opacity: number;
        transparent: boolean;
    };
    shape: {
        noiseScale: number;
        noiseSpeed: number;
        displace: number;
        roundness: number;
        pulse: number;
        chaos: number;
    };
    core: {
        visible: boolean;
        intensity: number;
        colorA?: string;
        colorB?: string;
    };
    bloom: number;
};

export const BLOB_PRESETS: BlobPreset[] = [
    {
        id: "chrome",
        name: "Chrome",
        swatch: "linear-gradient(135deg,#e6e9ee 0%,#9aa1ad 45%,#1f242c 100%)",
        bg: "#0a0a0c",
        accent: "#ffffff",
        material: {
            color: "#ffffff",
            metalness: 1.0,
            roughness: 0.18,
            envMapIntensity: 1.0,
            clearcoat: 0.0,
            clearcoatRoughness: 0.0,
            iridescence: 0.0,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.0,
            thickness: 1.2,
            ior: 1.45,
            attenuationColor: "#ffffff",
            attenuationDistance: 1.5,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: false,
        },
        shape: { noiseScale: 0.9, noiseSpeed: 0.3, displace: 0.32, roundness: 0.0, pulse: 0.1, chaos: 0.4 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "gold",
        name: "Gold",
        swatch: "linear-gradient(135deg,#ffe79a 0%,#d6a14a 50%,#553a18 100%)",
        bg: "#1a0e04",
        accent: "#ffc466",
        material: {
            color: "#ffd47a",
            metalness: 1.0,
            roughness: 0.18,
            envMapIntensity: 1.4,
            clearcoat: 0.4,
            clearcoatRoughness: 0.15,
            iridescence: 0.0,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.0,
            thickness: 1.2,
            ior: 1.45,
            attenuationColor: "#ffffff",
            attenuationDistance: 1.5,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: false,
        },
        shape: { noiseScale: 0.8, noiseSpeed: 0.25, displace: 0.28, roundness: 0.1, pulse: 0.0, chaos: 0.3 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "glass",
        name: "Glass",
        swatch: "linear-gradient(135deg,#dff5ff 0%,#88c8ff 50%,#1a3554 100%)",
        bg: "#091018",
        accent: "#9ed8ff",
        material: {
            color: "#ffffff",
            metalness: 0.0,
            roughness: 0.05,
            envMapIntensity: 1.2,
            clearcoat: 1.0,
            clearcoatRoughness: 0.0,
            iridescence: 0.15,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 1.0,
            thickness: 1.6,
            ior: 1.5,
            attenuationColor: "#bce8ff",
            attenuationDistance: 1.4,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: true,
        },
        shape: { noiseScale: 1.1, noiseSpeed: 0.22, displace: 0.22, roundness: 0.15, pulse: 0.05, chaos: 0.2 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "soap",
        name: "Soap Bubble",
        swatch: "linear-gradient(135deg,#fcc7ff 0%,#a5e8ff 45%,#cfffd6 100%)",
        bg: "#08111c",
        accent: "#c8e8ff",
        material: {
            color: "#ffffff",
            metalness: 0.0,
            roughness: 0.02,
            envMapIntensity: 1.6,
            clearcoat: 1.0,
            clearcoatRoughness: 0.0,
            iridescence: 1.0,
            iridescenceIOR: 1.6,
            iridescenceThicknessRange: [200, 1200],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 1.0,
            thickness: 0.4,
            ior: 1.33,
            attenuationColor: "#ffffff",
            attenuationDistance: 4.0,
            specularIntensity: 1.0,
            opacity: 0.95,
            transparent: true,
        },
        shape: { noiseScale: 1.2, noiseSpeed: 0.18, displace: 0.18, roundness: 0.35, pulse: 0.08, chaos: 0.15 },
        core: { visible: false, intensity: 0 },
        bloom: 0.45,
    },
    {
        id: "pearl",
        name: "Pearl",
        swatch: "linear-gradient(135deg,#fff6f0 0%,#e8d4ff 50%,#9ad0e8 100%)",
        bg: "#150c1a",
        accent: "#f4caff",
        material: {
            color: "#fbeefa",
            metalness: 0.6,
            roughness: 0.18,
            envMapIntensity: 1.3,
            clearcoat: 1.0,
            clearcoatRoughness: 0.05,
            iridescence: 0.85,
            iridescenceIOR: 1.8,
            iridescenceThicknessRange: [300, 700],
            sheen: 0.4,
            sheenColor: "#ffd6f5",
            sheenRoughness: 0.3,
            transmission: 0.0,
            thickness: 1.2,
            ior: 1.5,
            attenuationColor: "#ffffff",
            attenuationDistance: 1.5,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: false,
        },
        shape: { noiseScale: 0.7, noiseSpeed: 0.2, displace: 0.18, roundness: 0.4, pulse: 0.05, chaos: 0.1 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "plasma",
        name: "Plasma",
        swatch: "linear-gradient(135deg,#ff4dd6 0%,#a14bff 50%,#3027ff 100%)",
        bg: "#0c0420",
        accent: "#ff7ad9",
        material: {
            color: "#150028",
            metalness: 0.2,
            roughness: 0.15,
            envMapIntensity: 0.6,
            clearcoat: 1.0,
            clearcoatRoughness: 0.05,
            iridescence: 1.0,
            iridescenceIOR: 2.2,
            iridescenceThicknessRange: [350, 900],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.0,
            thickness: 1.2,
            ior: 1.7,
            attenuationColor: "#ffffff",
            attenuationDistance: 1.5,
            specularIntensity: 1.5,
            opacity: 1.0,
            transparent: false,
        },
        shape: { noiseScale: 1.3, noiseSpeed: 0.55, displace: 0.45, roundness: 0.0, pulse: 0.35, chaos: 0.85 },
        core: { visible: true, intensity: 1.4, colorA: "#ff4dd6", colorB: "#5a8cff" },
        bloom: 1.05,
    },
    {
        id: "lava",
        name: "Lava",
        swatch: "linear-gradient(135deg,#ffd25e 0%,#ff5b1f 45%,#3a0202 100%)",
        bg: "#1a0500",
        accent: "#ff7a30",
        material: {
            color: "#240602",
            metalness: 0.3,
            roughness: 0.55,
            envMapIntensity: 0.5,
            clearcoat: 0.6,
            clearcoatRoughness: 0.4,
            iridescence: 0.0,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.0,
            thickness: 1.2,
            ior: 1.4,
            attenuationColor: "#ffffff",
            attenuationDistance: 1.5,
            specularIntensity: 0.6,
            opacity: 1.0,
            transparent: false,
        },
        shape: { noiseScale: 0.95, noiseSpeed: 0.6, displace: 0.5, roundness: 0.0, pulse: 0.4, chaos: 0.9 },
        core: { visible: true, intensity: 1.6, colorA: "#ff8a1f", colorB: "#ffec85" },
        bloom: 1.25,
    },
    {
        id: "jelly",
        name: "Jelly",
        swatch: "linear-gradient(135deg,#9affd4 0%,#6affb4 45%,#0e3a26 100%)",
        bg: "#06180f",
        accent: "#7bf0c0",
        material: {
            color: "#7bf0c0",
            metalness: 0.0,
            roughness: 0.2,
            envMapIntensity: 1.0,
            clearcoat: 1.0,
            clearcoatRoughness: 0.1,
            iridescence: 0.0,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.85,
            thickness: 1.4,
            ior: 1.42,
            attenuationColor: "#5fe6a6",
            attenuationDistance: 1.0,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: true,
        },
        shape: { noiseScale: 1.0, noiseSpeed: 0.5, displace: 0.32, roundness: 0.45, pulse: 0.5, chaos: 0.25 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "wax",
        name: "Wax",
        swatch: "linear-gradient(135deg,#ffe2c2 0%,#e88ba6 50%,#5a2a48 100%)",
        bg: "#1c0a14",
        accent: "#ffafc4",
        material: {
            color: "#ffb7a8",
            metalness: 0.0,
            roughness: 0.55,
            envMapIntensity: 0.9,
            clearcoat: 0.2,
            clearcoatRoughness: 0.4,
            iridescence: 0.0,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 1.0,
            sheenColor: "#ff9bb6",
            sheenRoughness: 0.25,
            transmission: 0.55,
            thickness: 2.0,
            ior: 1.45,
            attenuationColor: "#ff8a9c",
            attenuationDistance: 0.8,
            specularIntensity: 0.6,
            opacity: 1.0,
            transparent: true,
        },
        shape: { noiseScale: 0.7, noiseSpeed: 0.18, displace: 0.22, roundness: 0.55, pulse: 0.05, chaos: 0.1 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "hologram",
        name: "Hologram",
        swatch: "linear-gradient(135deg,#5cf2ff 0%,#a35bff 50%,#ff5bd0 100%)",
        bg: "#020812",
        accent: "#7af0ff",
        material: {
            color: "#00121a",
            metalness: 0.3,
            roughness: 0.05,
            envMapIntensity: 1.4,
            clearcoat: 1.0,
            clearcoatRoughness: 0.0,
            iridescence: 1.0,
            iridescenceIOR: 2.4,
            iridescenceThicknessRange: [120, 920],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.5,
            thickness: 1.0,
            ior: 1.52,
            attenuationColor: "#9affff",
            attenuationDistance: 2.0,
            specularIntensity: 1.4,
            opacity: 1.0,
            transparent: true,
        },
        shape: { noiseScale: 1.1, noiseSpeed: 0.4, displace: 0.3, roundness: 0.05, pulse: 0.2, chaos: 0.6 },
        core: { visible: false, intensity: 0 },
        bloom: 0.55,
    },
    {
        id: "ink",
        name: "Ink",
        swatch: "linear-gradient(135deg,#1c1c1e 0%,#0a0a0c 50%,#000 100%)",
        bg: "#020203",
        accent: "#ffffff",
        material: {
            color: "#0a0a0c",
            metalness: 0.0,
            roughness: 0.18,
            envMapIntensity: 0.9,
            clearcoat: 1.0,
            clearcoatRoughness: 0.05,
            iridescence: 0.0,
            iridescenceIOR: 1.3,
            iridescenceThicknessRange: [100, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.0,
            thickness: 1.2,
            ior: 1.45,
            attenuationColor: "#ffffff",
            attenuationDistance: 1.5,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: false,
        },
        shape: { noiseScale: 1.4, noiseSpeed: 0.7, displace: 0.55, roundness: 0.0, pulse: 0.55, chaos: 1.0 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
    {
        id: "candy",
        name: "Candy",
        swatch: "linear-gradient(135deg,#ff5e9a 0%,#ffd35e 50%,#5cf2c4 100%)",
        bg: "#1a0710",
        accent: "#ff8ec4",
        material: {
            color: "#ff5e9a",
            metalness: 0.0,
            roughness: 0.15,
            envMapIntensity: 1.2,
            clearcoat: 1.0,
            clearcoatRoughness: 0.05,
            iridescence: 0.4,
            iridescenceIOR: 1.6,
            iridescenceThicknessRange: [200, 800],
            sheen: 0.0,
            sheenColor: "#ffffff",
            sheenRoughness: 0.4,
            transmission: 0.4,
            thickness: 1.0,
            ior: 1.5,
            attenuationColor: "#ffd1e3",
            attenuationDistance: 1.2,
            specularIntensity: 1.0,
            opacity: 1.0,
            transparent: true,
        },
        shape: { noiseScale: 0.9, noiseSpeed: 0.35, displace: 0.28, roundness: 0.3, pulse: 0.25, chaos: 0.4 },
        core: { visible: false, intensity: 0 },
        bloom: 0.32,
    },
];

export const BLOB_PRESET_BY_ID: Record<string, BlobPreset> = Object.fromEntries(
    BLOB_PRESETS.map((p) => [p.id, p]),
);

// keys we lerp every frame on the material/uniforms
export const NUMERIC_MAT_KEYS = [
    "metalness",
    "roughness",
    "envMapIntensity",
    "clearcoat",
    "clearcoatRoughness",
    "iridescence",
    "iridescenceIOR",
    "sheen",
    "sheenRoughness",
    "transmission",
    "thickness",
    "ior",
    "attenuationDistance",
    "specularIntensity",
    "opacity",
] as const;

export const COLOR_MAT_KEYS = ["color", "sheenColor", "attenuationColor"] as const;

export const SHAPE_KEYS = [
    "noiseScale",
    "noiseSpeed",
    "displace",
    "roundness",
    "pulse",
    "chaos",
] as const;
